// Deliberately separate test entry. Never imported by either application build.
const nativeTimeout=window.setTimeout.bind(window),nativeInterval=window.setInterval.bind(window),nativeRAF=window.requestAnimationFrame.bind(window);
const timers=new Set<number>(),intervals=new Set<number>(),frames=new Set<number>();
const t=window.setTimeout.bind(window),ct=window.clearTimeout.bind(window),i=window.setInterval.bind(window),ci=window.clearInterval.bind(window),r=window.requestAnimationFrame.bind(window),cr=window.cancelAnimationFrame.bind(window);
window.setTimeout=((fn:TimerHandler,ms?:number,...args:any[])=>{const id=t(()=>{timers.delete(id);if(typeof fn==='function')fn(...args);},ms);timers.add(id);return id;}) as typeof window.setTimeout;
window.clearTimeout=id=>{if(typeof id==='number')timers.delete(id);ct(id);};window.setInterval=((fn:TimerHandler,ms?:number,...args:any[])=>{const id=i(fn,ms,...args);intervals.add(id);return id;}) as typeof window.setInterval;
window.clearInterval=id=>{if(typeof id==='number')intervals.delete(id);ci(id);};window.requestAnimationFrame=fn=>{const id=r(now=>{frames.delete(id);fn(now);});frames.add(id);return id;};window.cancelAnimationFrame=id=>{frames.delete(id);cr(id);};
const listeners=new Map<string,Set<EventListenerOrEventListenerObject>>();for(const [label,target] of [['window',window],['document',document]] as const){const add=target.addEventListener.bind(target),remove=target.removeEventListener.bind(target);target.addEventListener=((type:string,fn:EventListenerOrEventListenerObject,options?:any)=>{const key=label+type+Boolean(typeof options==='boolean'?options:options?.capture);if(!listeners.has(key))listeners.set(key,new Set());listeners.get(key)!.add(fn);add(type,fn,options);}) as typeof target.addEventListener;target.removeEventListener=((type:string,fn:EventListenerOrEventListenerObject,options?:any)=>{listeners.get(label+type+Boolean(typeof options==='boolean'?options:options?.capture))?.delete(fn);remove(type,fn,options);}) as typeof target.removeEventListener;}
let audioOpen=0;const Audio=window.AudioContext;window.AudioContext=class extends Audio {constructor(...args:ConstructorParameters<typeof Audio>){super(...args);audioOpen++;}async close(){if(this.state!=='closed'){await super.close();audioOpen--;}}};
const [{createRoot},{ArcadeApp},{ArcadeRuntime},{OfficialController},{OfficialClient},{makeDefaultLocalContext},{MemoryScoreRepository}]=await Promise.all([import('react-dom/client'),import('../../../src/arcade/ArcadeApp'),import('../../../src/arcade/runtime'),import('../../../src/official/controller'),import('../../../src/official/client'),import('../../../src/platform/hostAdapter'),import('../../../src/services/scoreRepository')]);
let scenario='practice',context=makeDefaultLocalContext(),auth=0,attempts=0,submissions=0,cancels=0,reads=0,accepted=0,practiceResults=0,resumes=0,errors:string[]=[],status='ready';const hostListeners=new Set<any>();
const host={environment:'discord' as const,getContext:()=>context,subscribe:(f:any)=>{hostListeners.add(f);f(context);return()=>hostListeners.delete(f);},requestAuthentication:async()=>{auth++;return context;},continuePractice:()=>choose('practice'),dispose:()=>{},closeActivity:async()=>{},inviteOrShareActivity:async()=>{}};
const fetcher:typeof fetch=async(input,options)=>{const path=String(input),body=options?.body?JSON.parse(String(options.body)):{};let value:any={};if(options?.method==='GET')reads++;
 if(path.endsWith('/me'))value={status:'verified',player:{id:'fixture-player'},guild:{id:'fixture-guild'},csrf:'x'.repeat(43),officialAvailability:scenario==='other-server'?'other-server':scenario==='unavailable'?'unavailable':'eligible'};
 else if(path.endsWith('/stats'))value={acceptedCount:scenario==='empty'?'0':String(submissions),averageSeconds:'0',best:scenario==='empty'||!submissions?null:{ticks:60,attemptId:'fixture-accepted'}};
 else if(path.endsWith('/leaderboard')){if(scenario==='board-error')return Response.json({error:'private_internal_failure'},{status:503});value={entries:submissions&&scenario!=='empty'?[{playerTag:'fixture',displayName:'Fixture Player',ticks:60,rank:'1',isYou:true}]:[],ownEntry:null,record:null};}
 else if(path.endsWith('/submit')){submissions++;if(body.evidence.interruptions)practiceResults++;else accepted++;value={attemptId:body.attemptId,disposition:body.evidence.interruptions?'practice':'accepted',ticks:body.evidence.ticks,reason:'fixture',personalBest:submissions===1};}
 else if(path.endsWith('/cancel'))cancels++;
 else if(path.endsWith('/attempts')&&options?.method==='POST')value={attemptId:`fixture-${++attempts}`,rulesetId:'balance-replay-v1',tickRate:60,maxTicks:18000,retryDeadline:new Date(Date.now()+60000).toISOString()};
 else if(path.endsWith('/attempts'))value={attempts:[]};
 return Response.json(value);
};
const runtime=new ArcadeRuntime(host,new MemoryScoreRepository(),new OfficialController(new OfficialClient(fetcher,location.origin)));
function choose(value:string){scenario=value;context=makeDefaultLocalContext();hostListeners.forEach(f=>f(context));if(!['practice','auth-error'].includes(value))context={...context,environment:'discord',authenticated:true,arcadeSessionState:'verified',connectionState:'discord-authenticated',currentUser:{id:'fixture-player',displayName:'Fixture Player'},guildId:'fixture-guild'};if(value==='auth-error')context={...context,connectionState:'discord-error',connectionError:'timeout'};hostListeners.forEach(f=>f(context));}
createRoot(document.getElementById('root')!).render(<ArcadeApp runtime={runtime}/>);
document.getElementById('scenario')!.addEventListener('change',e=>choose((e.target as HTMLSelectElement).value));document.getElementById('back')!.addEventListener('click',()=>history.back());
window.addEventListener('error',()=>errors.push('page error'));window.addEventListener('unhandledrejection',()=>errors.push('unhandled rejection'));
const sleep=(ms:number)=>new Promise<void>(resolve=>nativeTimeout(resolve,ms));
const button=(name:string)=>Array.from(document.querySelectorAll<HTMLButtonElement>('#root button')).find(b=>b.textContent?.replace('→','').trim()===name&&!b.disabled);
async function until(test:()=>boolean,ms=20000){const end=performance.now()+ms;while(!test()){if(performance.now()>end)throw Error('bounded wait expired');await sleep(50);}}
const samples:any[]=[];let initialResources:any[]=[];let frameTimes:number[]=[];let last=0;const frame=(now:number)=>{if(last)frameTimes.push(now-last);last=now;if(frameTimes.length<600)nativeRAF(frame);};nativeRAF(frame);
const snapshot=()=>({timers:timers.size,intervals:intervals.size,frames:frames.size,listeners:Array.from(listeners.values()).reduce((n,s)=>n+s.size,0),audioOpen,canvases:document.querySelectorAll('canvas').length,hostListeners:hostListeners.size,auth,attempts,submissions,cancels,reads,accepted,practiceResults,resumes,heap:(performance as any).memory?.usedJSHeapSize??null});
nativeTimeout(()=>{initialResources=performance.getEntriesByType('resource').map((e:any)=>({name:e.name.split('/').pop(),bytes:e.encodedBodySize,duration:e.duration}));},3000);
nativeInterval(()=>{const sorted=[...frameTimes].sort((a,b)=>a-b);document.getElementById('metrics')!.textContent=JSON.stringify({status,scenario,route:runtime.destination,phase:runtime.phase,official:runtime.official.view.phase,current:snapshot(),samples,errors,frame:{count:sorted.length,p50:sorted[Math.floor(sorted.length*.5)],p95:sorted[Math.floor(sorted.length*.95)],max:sorted.at(-1)},initialResources},null,2);},500);
document.getElementById('soak')!.addEventListener('click',async()=>{if(status==='running')return;status='running';try{choose('official');await until(()=>!!button('Play Balance'));await sleep(8500);samples.push({stage:'initial',...snapshot()});
 for(let cycle=0;cycle<20;cycle++){button('Play Balance')!.click();await until(()=>!!button('Start Game'));button('Start Game')!.click();await until(()=>runtime.phase==='countdown');await sleep(100);button('Leave run · Back to Arcade')!.click();await until(()=>!!button('Play Balance'));await sleep(80);if([0,9,19].includes(cycle))samples.push({stage:`cancel-${cycle+1}`,...snapshot()});}
 async function completeRun(){await until(()=>{const resume=button('Resume');if(resume){resumes++;resume.click();}return runtime.phase==='results';},40000);await until(()=>['accepted','nonqualifying'].includes(runtime.official.view.phase));}
 for(let cycle=0;cycle<3;cycle++){button('Play Balance')!.click();await until(()=>!!button('Start Game'));button('Start Game')!.click();await completeRun();if(cycle===0){button('Play Again')!.click();await until(()=>runtime.phase!=='results');await completeRun();}button('Back to Arcade')!.click();await until(()=>!!button('Play Balance'));await sleep(8500);samples.push({stage:`completed-${cycle+1}`,...snapshot()});}
 for(let cycle=0;cycle<30;cycle++){button('Play Balance')!.click();await until(()=>!!button('Start Game'));button('Back to Arcade')!.click();await until(()=>!!button('Play Balance'));}
 await sleep(8500);samples.push({stage:'final',...snapshot()});if(snapshot().listeners!==samples[0].listeners||timers.size||intervals.size||frames.size)throw Error('resource cleanup mismatch');if(errors.length||audioOpen||document.querySelectorAll('canvas').length||hostListeners.size!==1||auth!==1||attempts!==24||submissions!==4||cancels!==20||accepted<1)throw Error('lifecycle count mismatch');status='passed';
 }catch(e){status='failed: '+(e instanceof Error?e.message:'test error');}});
