window.addEventListener('error',e=>{const p=document.createElement('pre');p.textContent='DIAGNOSTIC_ERROR';document.body?.append(p);});
(()=>{const events=[];const opts=new URLSearchParams(location.search);let start=performance.now(),stallDone=false;const nativeSet=setTimeout;const emit=(event,values={})=>{const row={event,ms:+(performance.now()-start).toFixed(2),...values};events.push(row);if(event==='SCENE_CREATE'&&Number(opts.get('warmup'))){const end=performance.now()+Number(opts.get('warmup'));while(performance.now()<end){}}if(opts.has('capture')&&event==='FRAME_RENDERED'&&[1,2,3,4,5,6].includes(values.frame)){const canvas=document.querySelector('.game-canvas canvas');if(canvas){const img=new Image();img.src=canvas.toDataURL();img.alt='Frame '+values.frame+' legacy '+values.legacy+' V004 '+values.v004;img.width=400;document.body.append(img);}}if(event==='CLOCK_FIRST'&&!stallDone&&Number(opts.get('stall'))){stallDone=true;nativeSet(()=>{emit('INJECT_STALL_START');const end=performance.now()+Number(opts.get('stall'));while(performance.now()<end){}emit('INJECT_STALL_END');},0);} };window.__diag={emit,events,opts};
for(const event of ['pointerdown','pointerup','pointercancel','focus','blur','pageshow','pagehide'])window.addEventListener(event,e=>emit('CAPTURE_'+event.toUpperCase(),{windowTarget:e.target===window,focused:document.hasFocus(),hidden:document.hidden}),true);
document.addEventListener('visibilitychange',()=>emit('DOCUMENT_VISIBILITY',{hidden:document.hidden}));window.addEventListener('message',e=>{if(e.data?.diagnostic==='focus') {emit('IFRAME_FOCUS_REQUEST');window.focus();}if(e.data?.diagnostic==='blur'){emit('IFRAME_BLUR_INJECT');window.dispatchEvent(new Event('blur'));}if(e.data?.diagnostic==='cancel'){emit('IFRAME_CANCEL_INJECT');window.dispatchEvent(new Event('pointercancel'));}});
new PerformanceObserver(l=>{for(const e of l.getEntries())if(e.name.includes('cdawg-mascot'))emit('ATLAS_RESOURCE',{duration:+e.duration.toFixed(2),transfer:e.transferSize,decodedBytes:e.decodedBodySize,end:+(e.responseEnd-start).toFixed(2)});}).observe({type:'resource',buffered:true});
try{new PerformanceObserver(l=>{for(const e of l.getEntries())emit('LONG_TASK',{duration:+e.duration.toFixed(2),start:+(e.startTime-start).toFixed(2)});}).observe({type:'longtask',buffered:true});}catch{}
for(const cls of [window.WebGLRenderingContext,window.WebGL2RenderingContext]){if(!cls)continue;const orig=cls.prototype.texImage2D;cls.prototype.texImage2D=function(...args){const t=performance.now();const v=orig.apply(this,args);const duration=performance.now()-t;if(duration>5)emit('GPU_TEXTURE_UPLOAD',{duration:+duration.toFixed(2)});return v;};}
if(opts.has('reduced')){const m=window.matchMedia.bind(window);window.matchMedia=q=>q.includes('prefers-reduced-motion')?{...m(q),matches:true,addEventListener(){},removeEventListener(){}}:m(q);}
let lastPhase='',lastCanvas=0;document.addEventListener('DOMContentLoaded',()=>{const output=document.createElement('pre');output.id='diagnostic-output';output.style='font:10px monospace;white-space:pre-wrap;max-height:180px;overflow:auto';document.body.append(output);const publish=()=>{const root=document.getElementById('root');const text=root?.textContent||'';let phase=root?.querySelector('.renderer-preparation')?(text.includes('could not get ready')?'error':'preparing'):text.includes('Your score is on hold')?'paused':root?.querySelector('.countdown')?'countdown':text.includes('Play Again')?'results':root?.querySelector('.game-canvas')?'playing':'home';if(phase!==lastPhase){emit('DOM_PHASE',{phase});lastPhase=phase;}const canvases=document.querySelectorAll('canvas').length;if(canvases!==lastCanvas){emit('DOM_CANVAS',{count:canvases});lastCanvas=canvases;}output.textContent=JSON.stringify({phase,events,listeners:window.__diag.resources?.()},null,2);if(window.parent!==window)window.parent.postMessage({diagnostic:'timeline',phase,events,listeners:window.__diag.resources?.()},location.origin);};setInterval(publish,100);publish();});
emit('DOCUMENT_START',{focused:document.hasFocus(),hidden:document.hidden});
})();
// Count only owned interruption/visibility listeners, not React's delegated DOM handlers.
(()=>{const counts=new Map();for(const [label,target]of [['window',window],['document',document]]){const add=target.addEventListener,remove=target.removeEventListener;const key=(type,options)=>label+type+Boolean(typeof options==='boolean'?options:options?.capture);target.addEventListener=function(type,fn,options){if(['focus','blur','visibilitychange'].includes(type)){const k=key(type,options);if(!counts.has(k))counts.set(k,new Set());counts.get(k).add(fn);}return add.call(this,type,fn,options);};target.removeEventListener=function(type,fn,options){counts.get(key(type,options))?.delete(fn);return remove.call(this,type,fn,options);};}window.__diag.resources=()=>Array.from(counts.values()).reduce((n,s)=>n+s.size,0);})();
