import assert from 'node:assert/strict';import {readFileSync,writeFileSync,readdirSync} from 'node:fs';import {execFileSync} from 'node:child_process';import {createHash} from 'node:crypto';import {gzipSync} from 'node:zlib';
const hash=b=>createHash('sha256').update(b).digest('hex');const report={};
report.assets=[];for(const group of ['balance0','balance1','reactions0','reactions1']){const path=`assets/brand/mascot/runtime/cdawg-mascot-${group}-v004.webp`;const bytes=readFileSync(path);const original=execFileSync('git',['show','main:'+path]);assert.equal(hash(bytes),hash(original));report.assets.push({group,bytes:bytes.length,sha256:hash(bytes)});}
assert.equal(execFileSync('git',['diff','main','--','server','shared','src/official','src/games/balance/simulationClock.ts','src/games/balance/simulation.ts','src/games/balance/config.ts','src/games/balance/interruption.ts','package-lock.json','assets','render.yaml'],{encoding:'utf8'}),'');
const scene=readFileSync('src/games/balance/BalanceScene.ts','utf8');assert.ok(!scene.includes('CdawgRig')&&!scene.includes('fallback'));
const files=dir=>readdirSync(dir,{withFileTypes:true}).flatMap(e=>e.isDirectory()?files(dir+'/'+e.name):[dir+'/'+e.name]);
const inventory=()=>Object.fromEntries([...files('dist'),...files('build')].map(path=>[path,hash(readFileSync(path))]));
report.inventory=inventory();report.frontendBytes=files('dist').reduce((n,p)=>n+readFileSync(p).length,0);report.jsGzipBytes=files('dist/assets').filter(p=>p.endsWith('.js')).reduce((n,p)=>n+gzipSync(readFileSync(p)).length,0);
const dangerous=[/-----BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY-----/,/\bAKIA[0-9A-Z]{16}\b/,/\bgh[pousr]_[A-Za-z0-9]{30,}\b/,/DUMMY_ONLY_ARTIFACT_SENTINEL|DUMMY_ONLY_DATABASE_SENTINEL/];
const production=files('dist').concat(files('build')).filter(p=>/\.(?:js|css|html|json)$/.test(p));for(const file of production){const text=readFileSync(file,'utf8');for(const pattern of dangerous)assert.ok(!pattern.test(text),'secret pattern in artifact');if(file.startsWith('dist/'))assert.ok(!/__diag|fixture-player|diagnostic-output|RENDERER_READY|arcade-lobby/.test(text),'diagnostic/lobby escaped into production');}
report.securityFiles=production.length;
const matrix=JSON.parse(readFileSync('docs/readiness/browser-matrix.json'));assert.equal(matrix.length,15);for(const run of matrix){assert.ok(!run.failure);const ev=run.events;for(const e of ev)for(const [key,value]of Object.entries(e)){assert.ok(!['token','identity','url','csrf','guildId','userId'].includes(key));if(typeof value==='string')assert.ok(!value.includes('://')&&!value.includes('?'));}if(!run.spec.stall)assert.ok(!ev.some(e=>e.event==='CLOCK_INTERRUPTED'));for(const e of ev.filter(e=>e.event==='SUBMIT')){assert.equal(e.ticks,42);assert.equal(e.interruptions,run.spec.stall?1:0);}}
report.browserCases=matrix.length;writeFileSync('tmp/readiness/validation.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({frontendBytes:report.frontendBytes,jsGzipBytes:report.jsGzipBytes,securityFiles:report.securityFiles,browserCases:report.browserCases}));
