import fs from 'node:fs';import {execFileSync} from 'node:child_process';import {tmpdir} from 'node:os';import {join,resolve,dirname} from 'node:path';import {createHash} from 'node:crypto';import {gzipSync,brotliCompressSync} from 'node:zlib';import assert from 'node:assert/strict';
const productionBaseline=process.argv.includes('--accepted-main');
const base=productionBaseline?'7fbc5f54730e719652a1f168ed815715dca00295':'fb8fa515f8113cbdad0e283cd72c5862d38c6883',out=productionBaseline?'tmp/soft-launch-integration':'tmp/iphone',env={PATH:dirname(process.execPath)+':'+process.env.PATH};
fs.mkdirSync(out,{recursive:true});
const archive=fs.mkdtempSync(join(tmpdir(),'arcade-soft-launch-'));execFileSync('tar',['-x','-C',archive],{input:execFileSync('git',['archive',base],{maxBuffer:512*1024*1024})});fs.symlinkSync(resolve('node_modules'),join(archive,'node_modules'));
const run=(cwd,args)=>execFileSync(process.execPath,args,{cwd,env,stdio:'inherit'});
const inventory=root=>Object.fromEntries(fs.readdirSync(root,{recursive:true}).filter(p=>fs.statSync(join(root,p)).isFile()).sort().map(p=>{const b=fs.readFileSync(join(root,p));return[p,{bytes:b.length,gzip:gzipSync(b).length,brotli:brotliCompressSync(b).length,sha256:createHash('sha256').update(b).digest('hex')}];}));
run(archive,['scripts/test-production.mjs']);const accepted={dist:inventory(join(archive,'dist')),build:inventory(join(archive,'build'))};
let first;for(let i=0;i<2;i++){run(process.cwd(),['scripts/test-production.mjs']);run(process.cwd(),['scripts/lobby/build.mjs']);const next={dist:inventory('dist'),build:inventory('build'),integration:inventory('tmp/lobby-integration/dist')};if(first)assert.deepEqual(next,first);first=next;}
for(const [p,v]of Object.entries(accepted.build))if(p!=='release.json')assert.equal(first.build[p].sha256,v.sha256,'server runtime changed '+p);
const total=map=>Object.fromEntries(['bytes','gzip','brotli'].map(k=>[k,Object.values(map).reduce((n,v)=>n+v[k],0)]));
const classify=files=>{const game=Object.fromEntries(Object.entries(files).filter(([p])=>/GameEntry-|mascot-/.test(p)));const sdk=Object.fromEntries(Object.entries(files).filter(([p])=>/embedded|sdk/i.test(p)));const initial=Object.fromEntries(Object.entries(files).filter(([p])=>!game[p]&&!sdk[p]));return{initial:total(initial),deferred:total(game),conditional:total(sdk),total:total(files)};};
// Identify conditional SDK by the graph's other JS chunk, rather than counting it in initial payload.
const grouping=(files,html)=>{const entry=html.match(/src="\/(assets\/[^" ]+\.js)"/)[1];const deferred=Object.fromEntries(Object.entries(files).filter(([p])=>/GameEntry-|mascot-/.test(p)));const conditional=Object.fromEntries(Object.entries(files).filter(([p])=>p.endsWith('.js')&&p!==entry&&!deferred[p]));const initial=Object.fromEntries(Object.entries(files).filter(([p])=>!deferred[p]&&!conditional[p]));return{initial:total(initial),deferred:total(deferred),conditional:total(conditional),total:total(files)};};
const a=grouping(accepted.dist,fs.readFileSync(join(archive,'dist/index.html'),'utf8')),c=grouping(first.dist,fs.readFileSync('dist/index.html','utf8'));
fs.writeFileSync(out+'/artifacts.json',JSON.stringify({base,archive,reproducible:true,serverUnchanged:true,accepted,candidate:first,totals:{accepted:a,candidate:c,delta:Object.fromEntries(Object.keys(a).map(k=>[k,Object.fromEntries(Object.keys(a[k]).map(n=>[n,c[k][n]-a[k][n]]))]))}},null,2));console.log(JSON.stringify({accepted:a,candidate:c}));
