import fs from 'node:fs';import assert from 'node:assert/strict';import {execFileSync} from 'node:child_process';import {createHash} from 'node:crypto';import {build} from 'vite';
const base='fb8fa515f8113cbdad0e283cd72c5862d38c6883';let checks=0;const ok=(v,m)=>{assert(v,m);checks++;};
const allowed=new Set(['src/main.tsx','src/arcade/ArcadeApp.tsx','src/games/balance/interruption.ts']);
for(const [file,addition] of [['src/main.tsx',"import './styles/mobile.css';\n"],['src/arcade/ArcadeApp.tsx',"import '../styles/mobile.css';\n"]])ok(fs.readFileSync(file,'utf8')===addition+execFileSync('git',['show',`${base}:${file}`],{encoding:'utf8'}),'non-mobile entry change: '+file);
const interruption=fs.readFileSync('src/games/balance/interruption.ts','utf8').split('\n').filter(line=>!line.includes("('pagehide', blur)")&&!line.includes("('freeze', blur)")).join('\n');ok(interruption===execFileSync('git',['show',`${base}:src/games/balance/interruption.ts`],{encoding:'utf8'}),'existing interruption/input behavior changed');
ok(fs.readFileSync('index.html','utf8')===execFileSync('git',['show',`${base}:index.html`],{encoding:'utf8'}).replace('width=device-width, initial-scale=1.0, user-scalable=no','width=device-width, initial-scale=1.0, viewport-fit=cover'),'unexpected HTML change');
const paths=execFileSync('git',['ls-tree','-r','--name-only',base],{encoding:'utf8'}).trim().split('\n');
for(const p of paths.filter(p=>/^(src|server|shared|config|assets\/brand\/(arcade|mascot))\//.test(p)||['package.json','package-lock.json','render.yaml','vite.config.ts'].includes(p))){if(allowed.has(p)||/\.test\.tsx?$/.test(p))continue;ok(fs.readFileSync(p).equals(execFileSync('git',['show',`${base}:${p}`],{maxBuffer:128*1024*1024})),`protected runtime/asset changed: ${p}`);}
const file='src/games/balance/BalanceExperience.tsx',before=execFileSync('git',['show',`${base}:${file}`],{encoding:'utf8'}),after=fs.readFileSync(file,'utf8');
for(const [start,end]of [['  const beginGameplay =','  const preparing ='],['  const pauseRun =','  const connectedOnce ='],["  useEffect(() => {\n    if (phase !== 'countdown'",'  const clearInput =']])ok(before.slice(before.indexOf(start),before.indexOf(end))===after.slice(after.indexOf(start),after.indexOf(end)),'readiness/countdown/official/input lifecycle changed');
ok(!after.includes('DevTuningControls')&&!after.includes('setTuning'),'diagnostics can alter tuning');
let graph;await build({mode:'production',logLevel:'silent',build:{write:false},plugins:[{name:'soft-launch-graph',generateBundle(_o,b){graph=Object.values(b).filter(x=>x.type==='chunk');}}]});
const entry=graph.find(x=>x.isEntry);ok(!Object.keys(entry.modules).some(x=>/phaser|BalanceScene/.test(x)),'game enters initial graph');ok(graph.some(x=>x.isDynamicEntry&&Object.keys(x.modules).some(p=>p.endsWith('/GameEntry.tsx'))),'game is not deferred');
ok(!graph.some(x=>Object.keys(x.modules).some(p=>/scripts\/|soft-launch\/v001\/CDAWG/.test(p))),'diagnostic or upload package in runtime');
const m=JSON.parse(fs.readFileSync('build/release.json'));for(const [p,h]of Object.entries(m.files))ok(createHash('sha256').update(fs.readFileSync('dist/'+p)).digest('hex')===h,'artifact hash mismatch');
fs.mkdirSync('tmp/iphone',{recursive:true});fs.writeFileSync('tmp/iphone/scope.json',JSON.stringify({base,checks,passed:true,protectedRuntime:true,deferredGame:true},null,2));console.log(`iPhone scope, readiness, immutable assets and graph passed: ${checks} checks`);
