// Local compiled fixtures only. Never calls a production origin or writes real scores.
import assert from 'node:assert/strict';import fs from 'node:fs';import {browser,sleep} from '../audio-readiness/cdp.mjs';
const out='tmp/soft-launch',rows=[],b=await browser(true,{diagnosticsPath:out+'/ui-cdp.jsonl'});
const state=async name=>{await b.evaluate(`(()=>{const s=document.querySelector('#scenario');s.value=${JSON.stringify(name)};s.dispatchEvent(new Event('change'));})()`);await sleep(350);};
const openSettings=async()=>{await b.evaluate("document.querySelector('#root .identity-button').click()");await b.until("!!document.querySelector('#root dialog[open]')");};
try{
 await b.send('Page.navigate',{url:'http://127.0.0.1:5231/lobby/index.html?dev=1&tuning=1'});await b.until("!!document.querySelector('.arcade-lobby')");
 for(const name of ['practice','official','empty','other-server','unavailable','board-error','stats-error','expired','auth-error','connecting','verifying','account-changed','signed-out','invalid-context','configuration']){
  await state(name);const visible=await b.evaluate("[...document.querySelectorAll('#root button,#root summary,#root input')].filter(e=>e.getBoundingClientRect().height).map(e=>e.textContent.trim()||e.getAttribute('aria-label')||e.type)");
  assert(!visible.includes('Dev'));if(['invalid-context','configuration','auth-error'].includes(name))assert(!visible.includes('Retry connection'),'redundant card recovery');await openSettings();
  if(name==='official'){for(const modifiers of [8,0]){await b.send('Input.dispatchKeyEvent',{type:'keyDown',key:'Tab',code:'Tab',windowsVirtualKeyCode:9,modifiers});await b.send('Input.dispatchKeyEvent',{type:'keyUp',key:'Tab',code:'Tab',windowsVirtualKeyCode:9,modifiers});assert(await b.evaluate("!!document.activeElement.closest('dialog[open]')"),'dialog focus escaped');}}
  const settings=await b.evaluate("document.querySelector('#root dialog').innerText");
  if(['official','empty','practice','other-server'].includes(name))assert(!settings.includes('Reconnect'),'healthy/practice reconnect');
  if(['auth-error','account-changed','signed-out'].includes(name))assert(settings.includes('Reconnect'),'missing contextual recovery');
  if(['invalid-context','configuration'].includes(name))assert(!settings.includes('Reconnect'),'unsupported retry');
  if(name==='verifying')assert(!settings.includes('Disconnect and practice'),'duplicate practice action');
  assert(!/PRIVATE|OAuth|session|ruleset|SDK|State:/.test(settings),'technical/private wording');
  await b.send('Input.dispatchKeyEvent',{type:'keyDown',key:'Escape',code:'Escape',windowsVirtualKeyCode:27});await b.send('Input.dispatchKeyEvent',{type:'keyUp',key:'Escape',code:'Escape',windowsVirtualKeyCode:27});await b.until("!document.querySelector('#root dialog[open]')");await b.until("document.activeElement.matches('.identity-button')",1000);assert(await b.evaluate("document.activeElement.matches('.identity-button')"),'focus not returned');rows.push({name,visible,settings,escapeFocus:true});
 }
 await state('practice');await openSettings();await b.evaluate("document.querySelector('.motion-preference input').click()");await b.click('Close');assert.equal(await b.evaluate("document.querySelector('.arcade-lobby').dataset.reduced"),'true');
 for(const [width,height]of [[1440,900],[800,600],[768,1024],[390,844],[375,667]]){
  await b.send('Emulation.setDeviceMetricsOverride',{width,height,deviceScaleFactor:1,mobile:width<500});await openSettings();
  const layout=await b.evaluate("(()=>{const d=document.querySelector('dialog[open]'),r=d.getBoundingClientRect();return{fits:r.left>=0&&r.right<=innerWidth&&r.top>=0&&r.bottom<=innerHeight,small:[...d.querySelectorAll('button,label,summary')].filter(e=>e.getBoundingClientRect().height>0&&e.getBoundingClientRect().height<44).map(e=>e.textContent)}})()");assert(layout.fits);assert.deepEqual(layout.small,[]);await b.click('Close');rows.push({viewport:[width,height],layout});
 }
 await b.send('Emulation.setDeviceMetricsOverride',{width:1280,height:900,deviceScaleFactor:1,mobile:false});
 await b.evaluate("localStorage.removeItem('cdawg.balance.help-seen.v1')");await b.click('Play practice');await b.until("!!document.querySelector('.balance-start-panel .balance-help')");assert(await b.evaluate("[...document.querySelectorAll('.balance-help')].some(e=>e.open)"),'first-time help missing');
 await b.click('Back to Arcade');await b.click('Play practice');await b.until("!!document.querySelector('.balance-start-panel')");assert(!await b.evaluate("[...document.querySelectorAll('.balance-help')].some(e=>e.open)"),'returning help opened');
 await b.evaluate("document.querySelector('.balance-start-panel summary').click()");assert(await b.evaluate("document.querySelector('.balance-start-panel details').open"));
 await b.click('Start Game');await b.until("!!document.querySelector('.result-panel')||!!document.querySelector('.pause-panel')");assert(!await b.evaluate("!!document.querySelector('.pause-panel')"));await b.click('Play Again');await b.until("!!document.querySelector('.result-panel')||!!document.querySelector('.pause-panel')");assert(!await b.evaluate("!!document.querySelector('.pause-panel')"));assert((await b.evaluate('document.querySelector(".result-panel").innerText')).toLowerCase().includes('practice score'));
 await b.click('Back to Arcade');await state('official');await b.click('Play Balance');await b.until("!!document.querySelector('.balance-start-panel')");await b.click('Start Game');await b.until("!!document.querySelector('.result-panel')||!!document.querySelector('.pause-panel')");assert(!await b.evaluate("!!document.querySelector('.pause-panel')"));await b.until("document.querySelector('.official-result')?.textContent.includes('Official score saved')");assert(!(await b.evaluate('document.querySelector(".result-panel").innerText')).toLowerCase().includes('practice score'));await b.click('View Leaderboard');await b.until("!!document.querySelector('.official-board')");assert(!/tick precision|verified Discord account/.test(await b.evaluate("document.querySelector('.official-board').innerText")));await b.click('Back to game');await b.click('Back to Arcade');
 assert.equal(await b.evaluate("document.querySelectorAll('#root canvas').length"),0);assert.equal(await b.evaluate("document.querySelectorAll('.arcade-lobby').length"),1);
 rows.push({help:'first-time visible; returning collapsed; reopening supported',practiceRuns:2,officialRuns:1,leaderboard:true,cleanup:true});
 fs.writeFileSync(out+'/ui-browser.json',JSON.stringify({status:'passed',rows},null,2));console.log(JSON.stringify({status:'passed',states:15,viewports:5,runs:3,focusReturns:15}));
}catch(e){fs.writeFileSync(out+'/ui-failure-dom.txt',await b.evaluate("document.querySelector('#root')?.innerText+'\\n'+document.querySelector('.result-panel')?.outerHTML"));fs.writeFileSync(out+'/ui-browser.json',JSON.stringify({status:'failed',error:e.message,rows},null,2));throw e;}finally{await b.close();}
