import fs from 'node:fs';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';import {execFileSync} from 'node:child_process';import sharp from '../mascot/preview/node_modules/sharp/lib/index.js';
const root='assets/brand/soft-launch/v001',out=root+'/CDAWG-Arcade-Discord-Upload-v001';
const inventory=()=>Object.fromEntries(fs.readdirSync(root,{recursive:true}).filter(p=>fs.statSync(root+'/'+p).isFile()).sort().map(p=>[p,createHash('sha256').update(fs.readFileSync(root+'/'+p)).digest('hex')]));
execFileSync(process.execPath,['scripts/soft-launch/export-brand.mjs']);const before=inventory();execFileSync(process.execPath,['scripts/soft-launch/export-brand.mjs']);assert.deepEqual(inventory(),before);
const m=JSON.parse(fs.readFileSync(out+'/manifest.json'));let checks=1;
for(const file of m.files){const b=fs.readFileSync(out+'/'+file.file),meta=await sharp(b).metadata();assert.equal(meta.width,file.width);assert.equal(meta.height,file.height);assert.equal(meta.format,file.format);assert.equal(createHash('sha256').update(b).digest('hex'),file.sha256);checks+=4;}
for(const size of [16,24,32,48,64,128,256]){const {data,info}=await sharp(out+`/specimen-icon-${size}-v001.png`).removeAlpha().raw().toBuffer({resolveWithObject:true});let cream=0,orange=0;for(let i=0;i<data.length;i+=info.channels){if(data[i]>180&&data[i+1]>160&&data[i+2]>130)cream++;if(data[i]>130&&data[i]>data[i+1]*1.25)orange++;}assert(cream>size*size*.04&&orange>0,'small-size tag contrast missing');checks++;}
const center=await sharp(out+'/04-embedded-background-1920x1080-v001.png').extract({left:640,top:360,width:640,height:360}).toBuffer();const bg=await sharp(center).stats();assert(bg.channels.slice(0,3).every(c=>c.stdev<.01),'embedded center not quiet');checks++;
for(const path of fs.readdirSync(root+'/source')){const s=fs.readFileSync(root+'/source/'+path,'utf8');assert(!/<script|onload=|href="https?:|@import/.test(s));checks++;}
fs.mkdirSync('tmp/soft-launch',{recursive:true});fs.writeFileSync('tmp/soft-launch/brand-validation.json',JSON.stringify({passed:true,checks,derivatives:m.files.length,specimens:[16,24,32,48,64,128,256],reproducible:true,centerQuiet:true,hashes:before},null,2));console.log(`Brand exports passed: ${checks} checks; byte-identical repeated exports`);
