import {describe,it,expect,vi} from 'vitest';
import {ArcadeSessionClient} from './sessionClient';
const view={status:'verified',player:{id:'234567890123456789',displayName:'Synthetic'},guild:{id:'345678901234567890'},expiresAt:'2026-09-10T00:00:00Z',idleExpiresAt:'2026-09-09T20:00:00Z',csrf:'c'.repeat(43)};
const response=(data:unknown,status=200)=>new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json'}});
describe('browser session transport',()=>{
  it('uses same-origin cookies and custom CSRF headers without storing the cookie or provider token',async()=>{const f=vi.fn<typeof fetch>().mockResolvedValueOnce(response(view)).mockResolvedValueOnce(response({status:'signed_out'}));const client=new ArcadeSessionClient(f,'https://arcade.example');await client.me();await client.logout();const init=f.mock.calls[1][1]!;expect(init.credentials).toBe('same-origin');expect(init.cache).toBe('no-store');expect(init.headers).toMatchObject({'X-Arcade-CSRF':view.csrf,'X-Arcade-Origin':'https://arcade.example','X-Arcade-Request':'1'});expect(init.body).toBe('{}');});
  it('returns disabled capability for legacy SDK authentication',async()=>{const client=new ArcadeSessionClient(vi.fn().mockResolvedValue(response({error:'sessions_unavailable'},503)),'https://arcade.example');expect(await client.challenge()).toBeNull();});
  it('starts a new challenge after expiration clears CSRF state',async()=>{const f=vi.fn<typeof fetch>().mockResolvedValueOnce(response(view)).mockResolvedValueOnce(response({error:'expired'},401)).mockResolvedValueOnce(response({challengeId:'synthetic',codeChallenge:'a'.repeat(43),codeChallengeMethod:'S256'}));const client=new ArcadeSessionClient(f,'https://arcade.example');await client.me();expect(await client.challenge()).toMatchObject({codeChallengeMethod:'S256'});expect(f.mock.calls[2][1]?.headers).not.toHaveProperty('X-Arcade-CSRF');});
  it('separates transient bootstrap token from session state',async()=>{const f=vi.fn().mockResolvedValue(response({...view,access_token:'transient-only'}));const client=new ArcadeSessionClient(f,'https://arcade.example');const result=await client.establish({challengeId:'synthetic',codeChallenge:'a'.repeat(43),codeChallengeMethod:'S256'},'code','instance');expect(result.access_token).toBe('transient-only');expect(JSON.stringify(result.session)).not.toContain('transient-only');});
  it('rejects forged numeric identity and raw error details',async()=>{const client=new ArcadeSessionClient(vi.fn().mockResolvedValue(response({...view,player:{id:234567890123456789}})),'https://arcade.example');await expect(client.me()).rejects.toThrow('Arcade session unavailable');const bad=new ArcadeSessionClient(vi.fn().mockResolvedValue(response({error:'PRIVATE_PROVIDER_TOKEN'},503)),'https://arcade.example');await expect(bad.me()).rejects.toMatchObject({code:'verification_unavailable'});});
});
