import {describe,it,expect,vi} from 'vitest';
import {OfficialController} from './controller';
import {OfficialClient} from './client';
import {TraceRecorder} from './trace';
import {SimulationClock,FIXED_STEP_MS} from '../games/balance/simulationClock';
import {balanceConfig} from '../../shared/balance/config';
import {replayBalance} from '../../server/attempts/replay';
const auth={attemptId:'00000000-0000-4000-8000-000000000099',rulesetId:'balance-replay-v1',tickRate:60,maxTicks:18000,retryDeadline:new Date(Date.now()+600000).toISOString()};
const accepted={attemptId:auth.attemptId,disposition:'accepted',ticks:42,reason:'accepted',personalBest:true,newGuildRecord:true};
function fixture(){const client={connect:vi.fn().mockResolvedValue('eligible'),begin:vi.fn().mockResolvedValue(auth),submit:vi.fn().mockResolvedValue(accepted),status:vi.fn().mockResolvedValue(accepted),stats:vi.fn().mockResolvedValue({acceptedCount:'1',best:{ticks:42}}),board:vi.fn().mockResolvedValue({entries:[],ownEntry:{rank:'1'},record:{ticks:42}}),cancel:vi.fn().mockResolvedValue({}),clear:vi.fn(),recent:vi.fn()};return {client,c:new OfficialController(client as unknown as OfficialClient)};}
describe('official experience',()=>{
 it('never starts official before authorization and prevents double Start',async()=>{const {c,client}=fixture();await c.connect('user','guild');let done!:(a:typeof auth)=>void;client.begin.mockImplementation(()=>new Promise(r=>{done=r;}));const pending=c.start();expect(c.view.phase).toBe('preparing');expect(await c.start()).toBe('busy');expect(client.begin).toHaveBeenCalledTimes(1);done(auth);expect(await pending).toBe('official');expect(c.view.phase).toBe('running');c.reset();});
 it.each(['practice','other-server','unavailable'])('keeps %s playable without issuance',async state=>{const {c,client}=fixture();client.connect.mockResolvedValue(state);await c.connect('u','g');expect(await c.start()).toBe('practice');expect(client.begin).not.toHaveBeenCalled();c.reset();});
 it('issuance failure requires a separate practice start',async()=>{const {c,client}=fixture();await c.connect('u','g');client.begin.mockRejectedValue(Error());expect(await c.start()).toBe('failed');expect(c.view.phase).toBe('unavailable');expect(await c.start()).toBe('practice');c.reset();});
 it('saves only after commit and refreshes stats/board',async()=>{const {c,client}=fixture();await c.connect('u','g');await c.start();let done!:(a:typeof accepted)=>void;client.submit.mockImplementation(()=>new Promise(r=>{done=r;}));const pending=c.finish(42);expect(c.view.phase).toBe('checking');expect(c.view.result).toBeNull();done(accepted);await pending;expect(c.view.phase).toBe('accepted');expect(c.view.result?.newGuildRecord).toBe(true);expect(client.stats).toHaveBeenCalledTimes(2);expect(client.board).toHaveBeenCalledTimes(2);c.reset();});
 it('interrupted evidence cannot be celebrated as official',async()=>{const {c,client}=fixture();await c.connect('u','g');await c.start();c.interrupt();client.submit.mockResolvedValue({...accepted,disposition:'practice',ticks:0,personalBest:false,newGuildRecord:false});await c.finish(42);expect(client.submit.mock.calls[0][1].interruptions).toBe(1);expect(c.view.phase).toBe('nonqualifying');expect(c.view.interrupted).toBe(true);c.reset();});
 it('rejects a contradictory accepted response for interrupted evidence',async()=>{const {c}=fixture();await c.connect('u','g');await c.start();c.interrupt();await c.finish(42);expect(c.view.phase).toBe('unconfirmed');expect(c.view.result).toBeNull();c.reset();});
 it('recovers a lost response without a second submission',async()=>{const {c,client}=fixture();await c.connect('u','g');await c.start();client.submit.mockRejectedValue(Error());await c.finish(42);expect(c.view.phase).toBe('unconfirmed');await c.retry();expect(c.view.phase).toBe('accepted');expect(client.submit).toHaveBeenCalledTimes(1);expect(client.begin).toHaveBeenCalledTimes(1);c.reset();});
 it('exact retry preserves canonical evidence and attempt',async()=>{const {c,client}=fixture();await c.connect('u','g');await c.start();c.trace.step(0,'left');client.submit.mockRejectedValueOnce(Error());client.status.mockRejectedValue(Error());await c.finish(42);await c.retry();expect(client.submit.mock.calls[0]).toEqual(client.submit.mock.calls[1]);expect(client.begin).toHaveBeenCalledTimes(1);c.reset();});
 it.each(['rejected','practice','expired'])('handles %s without saved/record state',async disposition=>{const {c,client}=fixture();await c.connect('u','g');await c.start();client.submit.mockResolvedValue({...accepted,disposition,ticks:0,personalBest:false,newGuildRecord:false});await c.finish(42);expect(c.view.phase).toBe('nonqualifying');c.reset();});
 it('account change discards pending result and trace',async()=>{const {c,client}=fixture();await c.connect('u','g');await c.start();let done!:(a:typeof accepted)=>void;client.submit.mockImplementation(()=>new Promise(r=>{done=r;}));const pending=c.finish(42);c.reset();done(accepted);await pending;expect(c.view.phase).toBe('practice');expect(c.view.result).toBeNull();expect(c.view.stats).toBeNull();c.reset();});
 it('late authorization cannot start a run after disconnect',async()=>{const {c,client}=fixture();await c.connect('u','g');let done!:(a:typeof auth)=>void;client.begin.mockImplementation(()=>new Promise(r=>{done=r;}));const pending=c.start();c.reset();done(auth);expect(await pending).toBe('failed');expect(c.view.phase).toBe('practice');});
 it('expired retry releases evidence and does not issue again',async()=>{vi.useFakeTimers();const {c,client}=fixture();client.begin.mockResolvedValue({...auth,retryDeadline:new Date(Date.now()+1000).toISOString()});await c.connect('u','g');await c.start();client.submit.mockRejectedValue(Error());await c.finish(42);await vi.advanceTimersByTimeAsync(1100);await c.retry();expect(client.submit).toHaveBeenCalledTimes(1);expect(c.view.phase).toBe('nonqualifying');c.reset();vi.useRealTimers();});
});
describe('effective trace and deterministic clock',()=>{
 it.each([30,60,120,144,240])('matches server replay at %i Hz',fps=>{const t=new TraceRecorder(),clock=new SimulationClock(balanceConfig,t);clock.frame(0,balanceConfig);const edges:[[number,number],...Array<[number,number]>]=[[4,-1],[10,1],[15,0],[22,-1],[29,1],[38,0]];for(const [tick,d]of edges)clock.input(d<0?'left':d>0?'right':'none',(tick+.5)*FIXED_STEP_MS);for(let i=1;i<1000&&!clock.finished;i++)clock.frame(i*1000/fps,balanceConfig);const e=t.freeze('balance-replay-v1',clock.ticks);expect(e.inputs).toEqual(edges);expect(e.ticks).toBe(63);expect(replayBalance(e).disposition).toBe('accepted');});
 it('deduplicates effective direction and bounds memory',()=>{const t=new TraceRecorder();for(let i=0;i<18000;i++)t.step(i,i%2?'left':'right');const e=t.freeze('balance-replay-v1',18000);expect(e.inputs).toHaveLength(4096);expect(e.interruptions).toBe(1);expect(JSON.stringify(e).length).toBeLessThan(65536);});
 it('omits redundant and after-terminal edges',()=>{const t=new TraceRecorder();t.step(0,'none');t.step(1,'left');t.step(2,'left');t.step(3,'none');expect(t.freeze('balance-replay-v1',3).inputs).toEqual([[1,-1]]);t.clear();t.step(4,'right');expect(t.freeze('balance-replay-v1',5).inputs).toEqual([]);});
});

describe('five-minute canonical cap',()=>{
 it('stops at 18,000 ticks and replays the golden cap',async()=>{
  const {readFileSync}=await import('node:fs');const golden=JSON.parse(readFileSync(new URL('../../scripts/fixtures/balance-cap-v1.json',import.meta.url),'utf8'));
  const t=new TraceRecorder(),clock=new SimulationClock(balanceConfig,t);clock.frame(0,balanceConfig);
  for(const [tick,d] of golden.inputs)clock.input(d<0?'left':d>0?'right':'none',(tick+.5)*FIXED_STEP_MS);
  for(let i=1;i<=18010&&!clock.finished;i++)clock.frame(i*FIXED_STEP_MS,balanceConfig);
  expect(clock.ticks).toBe(18000);expect(clock.finished).toBe(true);const e=t.freeze('balance-replay-v1',clock.ticks);expect(e.inputs).toEqual(golden.inputs);expect(replayBalance(e).ticks).toBe(18000);clock.frame(999999,balanceConfig);expect(clock.ticks).toBe(18000);
 });
});
