// Local source archives only; public dummy metadata; no provider or production access.
import {execFileSync} from 'node:child_process';
import fs from 'node:fs';
import {tmpdir} from 'node:os';
import {join,resolve,dirname} from 'node:path';
import {createHash} from 'node:crypto';
import {gzipSync,brotliCompressSync} from 'node:zlib';
import assert from 'node:assert/strict';
const baseline='cdc0d46e8c5366ef1bf1a22439e80d0502bfb277',out='tmp/release-b-reconciliation';fs.mkdirSync(out,{recursive:true});
const env={PATH:dirname(process.execPath)+':'+process.env.PATH};
const archive=ref=>{const dir=fs.mkdtempSync(join(tmpdir(),'arcade-release-b-'));execFileSync('tar',['-x','-C',dir],{input:execFileSync('git',['archive',ref],{maxBuffer:512*1024*1024})});fs.symlinkSync(resolve('node_modules'),join(dir,'node_modules'));return dir;};
const inventory=root=>Object.fromEntries(fs.readdirSync(root,{recursive:true}).filter(p=>fs.statSync(join(root,p)).isFile()).sort().map(p=>{const b=fs.readFileSync(join(root,p));return[p,{bytes:b.length,gzip:gzipSync(b).length,brotli:brotliCompressSync(b).length,sha256:createHash('sha256').update(b).digest('hex')}];}));
const run=(cwd,args)=>execFileSync(process.execPath,args,{cwd,env,stdio:'inherit'});
const accepted=archive(baseline),disabled=archive('HEAD');
fs.writeFileSync(join(disabled,'config/lobby-release.ts'),execFileSync('git',['show',baseline+':config/lobby-release.ts']));
for(const cwd of [accepted,disabled])run(cwd,['scripts/test-production.mjs']);
const a={dist:inventory(join(accepted,'dist')),build:inventory(join(accepted,'build'))},d={dist:inventory(join(disabled,'dist')),build:inventory(join(disabled,'build'))};
assert.deepEqual(d,a,'disabled candidate differs from accepted production under identical public metadata');
run(disabled,['scripts/lobby/build.mjs']);run(disabled,['scripts/lobby/validate-build.mjs']);
run(process.cwd(),['scripts/test-production.mjs']);run(process.cwd(),['scripts/lobby/build.mjs']);
const first={dist:inventory('dist'),build:inventory('build'),integration:inventory('tmp/lobby-integration/dist')};
run(process.cwd(),['scripts/test-production.mjs']);run(process.cwd(),['scripts/lobby/build.mjs']);
assert.deepEqual({dist:inventory('dist'),build:inventory('build'),integration:inventory('tmp/lobby-integration/dist')},first,'enabled builds are not reproducible');
for(const [p,f]of Object.entries(a.build))if(p!=='release.json')assert.equal(first.build[p]?.sha256,f.sha256,'server changed '+p);
const html=fs.readFileSync('dist/index.html','utf8'),entry=html.match(/src="\/(assets\/[^" ]+\.js)"/)[1];
const initial=Object.fromEntries(Object.entries(first.dist).filter(([p])=>p==='index.html'||p===entry||p.endsWith('.woff2')||p.endsWith('.svg')||p.includes('host-')||p.endsWith('.css')&&!p.includes('GameEntry-')));
const deferred=Object.fromEntries(Object.entries(first.dist).filter(([p])=>p.includes('GameEntry-')||p.includes('mascot-')));
const totals=map=>Object.fromEntries(['bytes','gzip','brotli'].map(k=>[k,Object.values(map).reduce((s,v)=>s+v[k],0)]));
const acceptedEntry=fs.readFileSync(join(accepted,'dist/index.html'),'utf8').match(/src="\/(assets\/[^" ]+\.js)"/)[1];
const acceptedInitial=Object.fromEntries(Object.entries(a.dist).filter(([p])=>p==='index.html'||p===acceptedEntry||p.endsWith('.css')));
const acceptedDeferred=Object.fromEntries(Object.entries(a.dist).filter(([p])=>p.includes('mascot-')));
const report={baseline,acceptedArchive:accepted,disabledArchive:disabled,disabledIdentical:true,reproducible:true,accepted:a,enabled:first,initial,deferred,totals:{accepted:totals(a.dist),acceptedInitial:totals(acceptedInitial),acceptedDeferred:totals(acceptedDeferred),enabled:totals(first.dist),initial:totals(initial),deferred:totals(deferred)}};
fs.writeFileSync(out+'/artifacts.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report.totals));
