import Phaser from 'phaser';
import {CdawgRig, getCdawgPoseForBalance} from '../../../src/games/balance/CdawgRig';
const $=(id:string)=>document.getElementById(id) as HTMLInputElement;
const state=$('state'),time=$('time'),play=$('play'),reduced=$('reduced'),light=$('light');
const preference=matchMedia('(prefers-reduced-motion: reduce)');reduced.checked=preference.matches;preference.addEventListener('change',e=>{reduced.checked=e.matches;refresh()});
let scenes:Workshop[]=[];let metadata:any;let measurements:any;
class Workshop extends Phaser.Scene {
 rig?:CdawgRig;sprite?:Phaser.GameObjects.Sprite;floor!:Phaser.GameObjects.Rectangle;candidate:boolean;loadStarted=0;loadedMs=0;
 constructor(candidate:boolean){super(candidate?'candidate':'current');this.candidate=candidate}
 preload(){this.loadStarted=performance.now();if(this.candidate){this.load.atlas('candidate','/cdawg-mascot-critical-v002.webp','/cdawg-mascot-critical-v002.json')}}
 create(){this.loadedMs=performance.now()-this.loadStarted;this.floor=this.add.rectangle(this.scale.width/2,this.scale.height*.8,Math.min(this.scale.width*.72,460),10,0xb77c43);if(this.candidate){if(this.textures.exists('candidate'))metadata=this.textures.get('candidate').customData;if(metadata?.meta)this.sprite=this.add.sprite(this.scale.width/2,this.scale.height*.8,'candidate','idle_default-00').setOrigin(.5,1)}else {this.measure();this.rig=new CdawgRig(this,this.scale.width/2,this.scale.height*.8-93)}this.scale.on('resize',()=>this.paint());scenes.push(this);refresh()}
 measure(){let width=0,height=0;for(const pose of ['idle','lean-left','lean-right','brace','wobble','panic','fall','impact','new-record-victory'] as const){for(let tilt=-34;tilt<=34;tilt+=1){for(const p of [0,1]){const r=new CdawgRig(this,0,0);r.setAngle(tilt*.74).setScale(1+p*.04+.08,1-p*.03-.04);r.applyPose(pose,p);const b=r.container.getBounds();width=Math.max(width,b.width);height=Math.max(height,b.height);r.container.destroy(true)}}}measurements={samples:1242,maxBounds:{width,height},strokeOverscan:4,renderCell:256,observedGameCanvases:{desktop:{viewport:[1280,900],canvas:[974,502]},narrow:{viewport:[390,844],canvas:[364,203],cssHeight:203.875}},source:'Unmodified CdawgRig; all nine states; tilt -34..34; panic endpoints; maximum pulse. Phaser RESIZE uses CSS pixels at both layouts.'}}
 paint(){const w=this.scale.width,h=this.scale.height;this.cameras.main.setBackgroundColor(light.checked?'#e8ddcc':'#1b1c20');this.floor.setPosition(w/2,h*.8).setSize(Math.min(w*.72,460),10);const name=state.value,t=reduced.checked?0:Number(time.value);const index=Math.round(t*11);if(this.candidate&&this.sprite&&metadata){const key=metadata.meta.clips[name]?.[index]??'idle_default-00';this.sprite.setFrame(key).setPosition(w/2,h*.8+metadata.meta.groundOffset);}
 if(this.rig){this.rig.container.destroy(true);this.rig=new CdawgRig(this,w/2,h*.8-93);const sign=name.includes('left')?-1:1;const panic=name==='panic'?1:name.startsWith('wobble')?.7:0;const tilt=(name.startsWith('lean')?24:name.startsWith('wobble')?29:0)*sign*(reduced.checked?0:t);this.rig.setAngle(tilt*.74).setScale(1+panic*.04,1-panic*.03);this.rig.applyPose(getCdawgPoseForBalance(tilt,panic,name==='fall',false,name==='victory_small'),panic)}
 }
 update(_:number,delta:number){if(this.candidate&&play.checked&&!reduced.checked){const before=Math.round(Number(time.value)*11);time.value=String((Number(time.value)+delta/1000/(23/24))%1);if(before!==Math.round(Number(time.value)*11))refresh()}}
}
function refresh(){for(const s of scenes)s.paint();if(measurements)$('metrics').textContent=JSON.stringify({...measurements,canvases:[...document.querySelectorAll('canvas')].map(c=>({width:c.width,height:c.height,cssWidth:c.getBoundingClientRect().width,cssHeight:c.getBoundingClientRect().height})),requestedMascotFiles:performance.getEntriesByType('resource').filter(e=>e.name.includes('cdawg-mascot-')).map(e=>new URL(e.name).pathname.split('/').pop()),loadMs:scenes.map(s=>({candidate:s.candidate,milliseconds:s.loadedMs})),renderer:scenes.map(s=>s.game.renderer.type===Phaser.WEBGL?'WebGL':'Canvas'),atlas:metadata?.meta},null,2);$('status').textContent=`${state.value} · frame ${reduced.checked?0:Math.round(Number(time.value)*11)} · ${reduced.checked?'Reduced motion: still pose':play.checked?'Playing at 12 samples/second':'Paused for reproducible review'} · ${metadata?'WebP atlas loaded in Phaser':'Atlas loading'}`}
for(const id of ['state','time','play','reduced','light'])$(id).addEventListener('input',refresh);
for(const candidate of [false,true])new Phaser.Game({type:Phaser.AUTO,parent:candidate?'new':'old',backgroundColor:'#1b1c20',scale:{mode:Phaser.Scale.RESIZE,width:'100%',height:'100%'},scene:new Workshop(candidate),audio:{noAudio:true},banner:false});
